### ISSUE TITLE
Add some introduce on pretrain and sft data

### ISSUE THREAD

**Issue by lucasjinreal** [DLCV-BUAA/TinyLLaVABench#1]
Opensource community would be benefit from it.

**Comment by baichuanzhou** [comment]
We expect to release all details in the following days. Meanwhile, please refer to our paper for more information. https://arxiv.org/abs/2402.14289

**Comment by baichuanzhou** [comment]
We have updated our README on [data preparation](https://github.com/DLCV-BUAA/TinyLLaVABench?tab=readme-ov-file#data-preparation)

**Comment by lucasjinreal** [comment]
@baichuanzhou  thanks, Do u think there any good data to enhance OCR ability? Currently I found the OCR ability especially Chinese are very weak.

**Comment by baichuanzhou** [comment]
@lucasjinreal Emmm, I think increasing data and increasing resolutions are both important to improve OCR abilities. As for training data, maybe look at ChartQA, DVQA, etc? Anyway, further exploration in this area is needed.

**Comment by lucasjinreal** [comment]
@baichuanzhou  How to enlarge the vit input size? since if make the size changed, the weights should not properly work
