### ISSUE TITLE
Is the SigLip model required just to perform inference?

### ISSUE THREAD

**Issue by plamb-viso** [DLCV-BUAA/TinyLLaVABench#10]
I'm trying to run inference on https://huggingface.co/bczhou/TinyLLaVA-2.0B. I've downloaded the model files and am trying to load them locally. When I run the builder file, it attempts to download bczhou/TinyLLaVA-2.0B-SigLIP as well. Is this really required for inference or only training?

**Comment by pengli-jc** [comment]
same question
