### ISSUE TITLE
可以给个微调的脚本吗？

### ISSUE THREAD

**Issue by LianghuiGuo** [DLCV-BUAA/TinyLLaVABench#15]
可以支持预训练和微调了吗？

**Comment by baichuanzhou** [comment]
不好意思现在才回复，微调脚本已更新。

**Comment by baichuanzhou** [comment]
> > 不好意思现在才回复，微调脚本已更新。
> 
> 微调脚本的这个TinyLLaVA-3.1B-SigLIP 是什么模型？好像下载不了，用vit替换可以吗？
> 
> ```
> --vision_tower bczhou/TinyLLaVA-3.1B-SigLIP \ 
> ```
可以替换为：google/siglip-so400m-patch14-384

**Comment by JalorOo** [comment]
> > > 不好意思现在才回复，微调脚本已更新。
> 
> > 
> 
> > 微调脚本的这个TinyLLaVA-3.1B-SigLIP 是什么模型？好像下载不了，用vit替换可以吗？
> 
> > 
> 
> > ```
> 
> > --vision_tower bczhou/TinyLLaVA-3.1B-SigLIP \ 
> 
> > ```
> 
> 可以替换为：google/siglip-so400m-patch14-384

好的，谢谢
