### ISSUE TITLE
Why is the forward method of the Vision Encoder decorated with @torch.no_grad?

### ISSUE THREAD

**Issue by Kend-AIL** [DLCV-BUAA/TinyLLaVABench#17]
While I'm attempting to fine-tune the vision encoder and encountering some issues, I believe the @torch.no_grad decoration is the key point. In the LLava source code, this is implemented to prevent modification of the vision encoder. However, it appears that you have provided the option '--tune_vision_tower' in the TrainingArguments. I suspect this is causing a conflict. Is this an oversight?

**Comment by baichuanzhou** [comment]
For some reason, the opensourced version did not comment the `no_grad` out. We have updated the correct version.

**Comment by Kend-AIL** [comment]
> For some reason, the opensourced version did not comment the `no_grad` out. We have updated the correct version. However, to make sure, I will review the results.

Thanks a lot, this works.
