### ISSUE TITLE
Is it convenient to provide some JSON files

### ISSUE THREAD

**Issue by wangfengjuan** [DLCV-BUAA/TinyLLaVABench#18]
![image](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/67569951/f74e8fcd-4813-4f7e-a621-8056ab787e80)
Good job, thank you for sharing, but during the verification process, I need some files. Would it be convenient for you to provide them? val_predictions.json and val_attentions.json thankyou！

**Comment by baichuanzhou** [comment]
Which eval process is this?

**Comment by wangfengjuan** [comment]
> Which eval process is this?
![image](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/67569951/4a7bf49d-f97a-4415-801e-5547074a0037)

When performing gqa validation, these two files are missing in the eval. py file

**Comment by baichuanzhou** [comment]
Please provide the full error message so I could have an idea of what is really missing here.🤓

**Comment by wangfengjuan** [comment]
> Please provide the full error message so I could have an idea of what is really missing here.🤓

![image](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/67569951/c7fac73a-e9b0-424e-8390-27c4f4a15f4f)
Missing this file

**Comment by baichuanzhou** [comment]
It’s a little confusing since I don’t know what exactly happened. Did you following the instructions in Evaluation.md to download eval data first? What script were you running? Eval scripts should be self-contained so I need to have a clearer idea of what you did.

**Comment by wangfengjuan** [comment]
> It’s a little confusing since I don’t know what exactly happened. Did you following the instructions in Evaluation.md to download eval data first? What script were you running? Eval scripts should be self-contained so I need to have a clearer idea of what you did.

I have downloaded the relevant data required for validation on the GQA dataset and now run the script: CUDA_VISIBLE-DEVICES=0 bash scripts/tiny_llava/eval/gqa. sh. Then there was a problem of missing the following files, which were not included in the downloaded validation dataset or the data you provided.Looking forward to your reply, thank you!

I have downloaded the relevant data required for validation on the GQA dataset and now run the script: CUDA_VISIBLE-DEVICES=0 bash scripts/tiny_llava/eval/gqa. sh. Then there was a problem of missing the following files, which were not included in the downloaded validation dataset or the data you provided. Looking forward to your reply, thank you!
![image](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/67569951/77e14029-fc51-4141-8b6d-565502c306d6)

**Comment by baichuanzhou** [comment]
The error message you provided indicates that you ran `python eval/eval.py --tier val` instead of `python eval/eval.py --tier testdev_balanced` in your `gqa.sh` file. Please change back to `python eval/eval.py --tier testdev_balanced` so that evals can be run correctly.

**Comment by baichuanzhou** [comment]
This issue will be closed in 1 day due to inactivity.
