### ISSUE TITLE
WARNING: tokenization mismatch: 0 vs

### ISSUE THREAD

**Issue by G-JWLee** [DLCV-BUAA/TinyLLaVABench#20]
Hello, thank you for your great work!

When training the TinyLLaVA-2B, I got quite a lot of warning messages:

WARNING: tokenization mismatch: 0 vs. N. (ignored)

This caused some samples ignored.

I found that this happens in 245723-th instruction tuning sample of LLaVA 665k dataset:

USER: <image>\nWould this person be more likely to be a type a or b person?\nAnswer the question using a single word or phrase. ASSISTANT:"

I did not get this message when training the LLaVA-1.5 7B.

**Comment by gujiaqivadin** [comment]
I met the same problem, how to solve it, thx!
