### ISSUE TITLE
ModuleNotFoundError: No module named 'tinyllava'

### ISSUE THREAD

**Issue by JalorOo** [DLCV-BUAA/TinyLLaVABench#21]
How to fix?

llava-1.5-7b can run normally, but this tiny can not.

**Comment by baichuanzhou** [comment]
Please follow the setup instructions in README🫡

**Comment by JalorOo** [comment]
> Please follow the setup instructions in README🫡

OK, thanks

**Comment by JalorOo** [comment]
> Please follow the setup instructions in README🫡

It works !!! thank you !
