### ISSUE TITLE
cls not defined!

### ISSUE THREAD

**Issue by JalorOo** [DLCV-BUAA/TinyLLaVABench#22]
![2024-03-15 12-11-22 的屏幕截图](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/20612722/fe343adb-dcc6-4cb8-b79f-e5893305e7be)

![2024-03-15 12-13-22 的屏幕截图](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/20612722/8bc672e7-9ecb-44e6-ae42-dc66ac7fb3fc)

It seems to be a bug?

**Comment by baichuanzhou** [comment]
Yep, it was a branch mixup. Fixes have been pushed to main now.

**Comment by JalorOo** [comment]
It works !
