### ISSUE TITLE
Can Tiny Llama 1.5B lora finetune in one 24GB gpu?

### ISSUE THREAD

**Issue by JalorOo** [DLCV-BUAA/TinyLLaVABench#23]
I try lora finetune, it seems tiny llama only support full finetune now.

**Comment by baichuanzhou** [comment]
Finetuning TinyLLaVA with Phi is possible with 24GB gpu.

I used this script to finetune TinyLLaVA-3.1B with LoRA on the [pokemon dataset](https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions).

**Please replace the data path to yours**
```bash
#!/bin/bash

# Assign the arguments to variables
DATA_PATH="/path/to/your/pokemon_blip_captions.json"
IMAGE_PATH="/path/to/your/data/"
OUTPUT_DIR="/path/to/your/TinyLLaVA-3.1B-lora"

deepspeed tinyllava/train/train.py \
    --deepspeed ./scripts/tiny_llava/zero3.json \
    --lora_enable True --lora_r 32 --lora_alpha 64 \
    --model_name_or_path bczhou/TinyLLaVA-3.1B \
    --version phi \
    --data_path $DATA_PATH \
    --image_folder $IMAGE_PATH\
    --vision_tower bczhou/TinyLLaVA-3.1B-SigLIP \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length False \
    --fp16 True \
    --output_dir $OUTPUT_DIR \
    --num_train_epochs 3 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 3072 \
    --gradient_checkpointing True \
    --dataloader_num_workers 15 \
    --lazy_preprocess True \
    --report_to wandb \
```
I used this script to convert the [pokemon dataset](https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions):
```python
import shortuuid
from datasets import load_dataset
from PIL import Image
import random
import json
import tqdm
import os

ds = load_dataset('lambdalabs/pokemon-blip-captions')
pokemon_data = []

pokemon_image_path = '/path/to/your/data/pokemon/image'
pokemon_data_path = '/path/to/your/pokemon_blip_captions.json'

description_list = [
    "Describe the image concisely.",
    "Provide a brief description of the given image.",
    "Offer a succinct explanation of the picture presented.",
    "Summarize the visual content of the image.",
    "Give a short and clear explanation of the subsequent image.",
    "Share a concise interpretation of the image provided.",
    "Present a compact description of the photo's key features.",
    "Relay a brief, clear account of the picture shown.",
    "Render a clear and concise summary of the photo.",
    "Write a terse but informative summary of the picture.",
    "Create a compact narrative representing the image presented."
]

for sample in tqdm.tqdm(ds['train']):
    uuid = shortuuid.uuid()
    sample_dict = dict()
    sample_dict['id'] = uuid
    sample_dict['image'] = 'pokemon/image/' + uuid + '.jpg'
    sample['image'].save(os.path.join(pokemon_image_path, uuid + '.jpg'))
    conversations = [
        {"from": "human", "value": "<image>\n" + random.choice(description_list)},
        {"from": "gpt", "value": sample['text']}
    ]
    sample_dict['conversations'] = conversations
    pokemon_data.append(sample_dict)

with open(pokemon_data_path, 'w') as f:
    json.dump(pokemon_data, f, indent=4)
```
The experiment took approximately 10 minutes with one 4090.
Let me know if you have anymore questions! I am writing a tutorial doc on finetuning with LoRA, if you are interested, please contribute.

**Comment by JalorOo** [comment]
ok, i use the code, it works!

**Comment by AleNunezArroyo** [comment]
I was already able to do the training, with the [guide](https://github.com/DLCV-BUAA/TinyLLaVABench/blob/main/docs/CUTOM_FINETUNE.md). The files that it generates are the following: 
![image](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/50973610/c31edb86-1a39-467c-a790-0b74df8fe092)

But using the reference codes in the repository, I get this error. 
![image](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/50973610/9dbf1b96-bad6-43ec-9811-fcd665cbf8be)

![image](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/50973610/08106e1a-0619-4df4-ac22-087c8c7e690c)

What code should I use for the model that has the finetune? Thank you.

**Comment by JalorOo** [comment]
> I was already able to do the training, with the [guide](https://github.com/DLCV-BUAA/TinyLLaVABench/blob/main/docs/CUTOM_FINETUNE.md). The files that it generates are the following: ![image](https://private-user-images.githubusercontent.com/50973610/316935990-c31edb86-1a39-467c-a790-0b74df8fe092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjgyMTcsIm5iZiI6MTcxMTUyNzkxNywicGF0aCI6Ii81MDk3MzYxMC8zMTY5MzU5OTAtYzMxZWRiODYtMWEzOS00NjdjLWE3OTAtMGI3NGRmOGZlMDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA4MjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MGMyNzdmNzU1YzEzY2RkNzkwOWU5Yzg0MjllNTkzM2I5NmE4ZDczOWFiZTY4OTE3Yzk4OTAxYTQ4OTVhMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.azjcXyPbvTisXv9ZbKhZFuEoJ_cANvJbVi1mLr4fMJQ)
> 
> But using the reference codes in the repository, I get this error. ![image](https://private-user-images.githubusercontent.com/50973610/316939933-9dbf1b96-bad6-43ec-9811-fcd665cbf8be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjgyMTcsIm5iZiI6MTcxMTUyNzkxNywicGF0aCI6Ii81MDk3MzYxMC8zMTY5Mzk5MzMtOWRiZjFiOTYtYmFkNi00M2VjLTk4MTEtZmNkNjY1Y2JmOGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA4MjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNDg4NDQ4NDExZDg3YThhMWM4NmJjYWY2YTQxOTJiOGU1MWFiMGE3MWE3YTM3NjA4MThiMDIwZDM3MTU3NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3Pa2QDSDWamI-EiqBjgWcnb-m2RbEnCbms7mpOkrUQ)
> 
> ![image](https://private-user-images.githubusercontent.com/50973610/316940048-08106e1a-0619-4df4-ac22-087c8c7e690c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjgyMTcsIm5iZiI6MTcxMTUyNzkxNywicGF0aCI6Ii81MDk3MzYxMC8zMTY5NDAwNDgtMDgxMDZlMWEtMDYxOS00ZGY0LWFjMjItMDg3YzhjN2U2OTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA4MjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjA3NDQxOWZjYTFlMWJlOWIyNGE3ZDdmMmUyYmZjYmRiYmY4MGM1MjA0YjY3ZWVkMjdhNjM2MDNkYTk3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ri2fkKhG2zGlrE7JU-oSGHnBhiyrpuyLX9mCiCVP5V4)
> 
> What code should I use for the model that has the finetune? Thank you.

firstly, you need to merge the lora weight into the origin model. 
next, you need to make sure the folder name of your store merged weight have the ''lora" word.
![2024-03-27 16-28-12 的屏幕截图](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/20612722/95a8e641-11a4-4de5-82d2-e848a59d5dd2)
![2024-03-27 16-29-55 的屏幕截图](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/20612722/30eb77cf-462b-44ab-9159-3f05007c6e11)

**Comment by JalorOo** [comment]
more detail you can find my open source code [https://github.com/Libv-Team/figlang2024](https://github.com/Libv-Team/figlang2024)

**Comment by AleNunezArroyo** [comment]
> more detail you can find my open source code https://github.com/Libv-Team/figlang2024

Thank you very much for the information and for the repository, it is already working 😊

**Comment by JalorOo** [comment]
> > more detail you can find my open source code https://github.com/Libv-Team/figlang2024
> 
> Thank you very much for the information and for the repository, it is already working 😊

you are welcome! 😊
