### ISSUE TITLE
 Inference seems can't work

### ISSUE THREAD

**Issue by JalorOo** [DLCV-BUAA/TinyLLaVABench#29]
![2024-03-16 17-35-27 的屏幕截图](https://github.com/DLCV-BUAA/TinyLLaVABench/assets/20612722/cc3d9b61-deb8-4e4c-9ef0-117dc4353647)

 Inference seems can't work with the 1.5B model

**Comment by baichuanzhou** [comment]
change the `conv` mode to `v1` as specified in README
