### ISSUE TITLE
Dataset usage

### ISSUE THREAD

**Issue by LinB203** [DLCV-BUAA/TinyLLaVABench#3]
Gread job!
I'd like to confirm that both sharegpt4v and llava data were used to train the model.

**Comment by baichuanzhou** [comment]
Yes, we use both sharegpt4v and llava data to train the model. We provide detailed descriptions of training data and recipes at Section 4.1.2 of our paper. TinyLLaVA-3.1B was trained on the share recipe with ShareGPT4V’s pretraining data and sft data(mostly llava data).
We will provide descriptions of data preparation and model initialization some time today.
Great job on MoE😊
