### ISSUE TITLE
Saving vision tower in checkpointing

### ISSUE THREAD

**Issue by zhangliang-04** [DLCV-BUAA/TinyLLaVABench#35]
Dear authors,

Thanks for your great work! I notice that when set `tune_entire_model=True`, the code will automatically save the trained vision tower model after entire training process. However, it seems that the vision tower is not saved in intermediate checkpoints, which make the checkpoints unusable. Can you provide any suggestions to fix this?

**Comment by baichuanzhou** [comment]
You can implement saving vision tower in trainer._save method.

**Comment by zhangliang-04** [comment]
OK. Thanks for you advice!
