### ISSUE TITLE
Fine-tuning on A6000 GPU

### ISSUE THREAD

**Issue by soham-joshi** [DLCV-BUAA/TinyLLaVABench#40]
I am fine-tuning the the variant "bczhou/TinyLLaVA-1.5B" on a custom Text-VQA dataset on an NVIDIA-RTX A6000 (50 GBs of VRAM). Could you let me know how much VRAM is typically used for full-finetuning (Not LLoRA) in this case? I am getting CUDA out of memory so I think I am doing something wrong.
Moreover, if you know any VRAM optimization strategies (already implemented in your code and you have the args for it to feed it to the training module), could you share that info also?

I am taking [this](https://github.com/DLCV-BUAA/TinyLLaVABench/blob/dev/scripts/tiny_llava/finetune/finetune.sh) as a reference for the fine-tuning script.

@baichuanzhou @huangleiBuaa @eltociear @jiajunlong 

Thanks!

**Comment by baichuanzhou** [comment]
We support flash-attention, [here](https://github.com/DLCV-BUAA/TinyLLaVABench/blob/main/tinyllava/train/train.py#L70). 

We used 8xA100(40G) to train and finetune our models.

**Comment by sahil02235** [comment]
@baichuanzhou For H100, it asking for torch upgrade. This version doesnt support.
