### ISSUE TITLE
Compute budget for TinyLLaVA?

### ISSUE THREAD

**Issue by ryan-caesar-ramos** [DLCV-BUAA/TinyLLaVABench#45]
Hi! Can I ask

1. What GPUs were used in training these models? Were they A100s?
2. How many of these GPUs were used?
3. How many hours did it take to finish training?

Thank you!

**Comment by baichuanzhou** [comment]
1. Models were trained on A100(40GB)s.
2. It took 8 of A100s.
3. For the largest model, it took approximately 12 hours.

**Comment by ryan-caesar-ramos** [comment]
Thanks for the reply! Can I ask if the 12 hours was for everything i.e. the pre-training and the fine-tuning all competed within a total of 12 hours?

**Comment by baichuanzhou** [comment]
This issue is marked as closed as questions have been answered through emails.
