### ISSUE TITLE
can not get the same GQA and MME results using the official TinyLLaVA-1.5B weights

### ISSUE THREAD

**Issue by YFCYFC** [DLCV-BUAA/TinyLLaVABench#48]
Hi，brilliant work！And the problem I'm faced with is I can not get the same GQA and MME results using the official  TinyLLaVA-1.5B weights from https://huggingface.co/bczhou/TinyLLaVA-1.5B/.I use the official bash scripts to conduct the evaluations with the  minor changes that are not relevant to the evaluating logics.There must be something wrong I've done.
And the MME result:
<img width="461" alt="image" src="https://github.com/DLCV-BUAA/TinyLLaVABench/assets/23159695/9336dde6-b872-46fe-b145-e2a84c87c9e2">
the GQA result:
<img width="245" alt="image" src="https://github.com/DLCV-BUAA/TinyLLaVABench/assets/23159695/6c14ea6e-e89a-4742-8d99-750182006035">

Thanks a lot!

**Comment by baichuanzhou** [comment]
Try changing the `conv_mode` to `v1`

**Comment by YFCYFC** [comment]
> Try changing the `conv_mode` to `v1`
Thank you for your rapid reply.Change 'conv_mode' to 'v1' works for me, and I realize that I took tiny_llama as conv_mode for granted for Tinyllava-1.5B and I missed the important information in readme.For the ones who would encounter the similar problems:
<img width="800" alt="image" src="https://github.com/DLCV-BUAA/TinyLLaVABench/assets/23159695/b4a77c92-a2e6-49bb-a40b-14ce3afe905c">
Thank you again for the perfect job.
