### ISSUE TITLE
Problem about ShareGPT4V SFT supervised finetune dataset

### ISSUE THREAD

**Issue by YFCYFC** [DLCV-BUAA/TinyLLaVABench#49]
Hi，I am confused about the training data of  ShareGPT4V mentioned in the paper, specifically, the ShareGPT4V-mix-665k dataset.As the paper says: 
ShareGPT4V-SFT dataset is similar to LLaVA-1.5-SFT, with the exception that the 23K detailed description data in LLaVA-1.5-SFT being replaced with detailed captions randomly sampled from the 100K ShareGPT4V data.
The problem is how I can reproduce the exact result without knowing how to randomly sample 23K in the ShareGPT4V to replace the LLaVA-1.5-SFT data.And I don't find plausible explanation on the problem, if I missed import information, feel free to notify me。
Another problem is that why should we replace the 23K description data in LLaVA-1.5-SFT?Are they poorly labeled? 
Looking for your reply.THANK YOU!

**Comment by baichuanzhou** [comment]
In the paper, we briefly summarized the difference between [ShareGPT4V's SFT data](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V/blob/main/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json) and [LLaVA-1.5's SFT data](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/blob/main/llava_v1_5_mix665k.json). We ourselves did not perform such resampling or swapping. To reproduce results, you should download the [ShareGPT4V's SFT data](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V/blob/main/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json).

**Comment by YFCYFC** [comment]
> In the paper, we briefly summarized the difference between [ShareGPT4V's SFT data](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V/blob/main/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json) and [LLaVA-1.5's SFT data](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/blob/main/llava_v1_5_mix665k.json). We ourselves did not perform such resampling or swapping. To reproduce results, you should download the [ShareGPT4V's SFT data](https://huggingface.co/datasets/Lin-Chen/ShareGPT4V/blob/main/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.json).

Thank you,I figure it out now.The reason why I made this mistake is that I didn't know about ShareGPT4V and its features, I need to refer to [this work](https://arxiv.org/pdf/2311.12793.pdf) and learn more about the dataset.

**Comment by baichuanzhou** [comment]
Consider giving us a star if you like our project.

**Comment by YFCYFC** [comment]
> Consider giving us a star if you like our project.
Sure.Of course.
