### ISSUE TITLE
Error when inferencing TinyLLaVA-1.5B

### ISSUE THREAD

**Issue by eternalding** [DLCV-BUAA/TinyLLaVABench#8]
Greetings.
When inferencing w/ TinyLLaVA-1.5B, a runtime error occurs with following response:
"RuntimeError: The size of tensor a (2) must match the size of tensor b (7) at non-singleton dimension 0"

I think the root cause of this is from the implementation of in KeywordsStoppingCriteria:
https://github.com/DLCV-BUAA/TinyLLaVABench/blob/main/tinyllava/mm_utils.py#L240

When matching output_ids and keyword_id, if current output_id is shorter than keyword_id, using
`
            if (output_ids[0, -keyword_id.shape[0]:] == keyword_id).all():
`
will cause output_ids[0, -keyword_id.shape[0]:] and keyword_id to have unequal size.

A way to fix this is:
`
if (output_ids.shape[1] >= keyword_id.shape[0])  and (output_ids[0, -keyword_id.shape[0]:] == keyword_id).all():
`

If this solution looks good to you, is it OK for me to submit an MR for this update?

Best,
YC

**Comment by baichuanzhou** [comment]
Hi, may I see what prompt caused this problem?
Also, we added new descriptions for how to set up inference examples. See [here](https://github.com/DLCV-BUAA/TinyLLaVABench?tab=readme-ov-file#important). 😊

**Comment by baichuanzhou** [comment]
[Here](https://github.com/DLCV-BUAA/TinyLLaVABench?tab=readme-ov-file#important), we specified what prompt mode you should use to set up inference. For the 1.5B model, use `v1` mode.

**Comment by eternalding** [comment]
Understood. Thanks for the reply, but this also limits the possibility to change custom system prompt.
Will it be better to update KeywordsStoppingCriteria so 1.5B could support other conv_mode?
If you suggest not to change it, then I'll close this issue. Thanks.

**Comment by baichuanzhou** [comment]
From my perspective, keyword_id should be tokenized into one input id? TinyLlama's example failed because its tokenizer tokenized `|<endoftext>|` into two ids, which in my case should not happen. If you want to change your system prompt, you can add more `conv_mode` in [here](https://github.com/DLCV-BUAA/TinyLLaVABench/blob/main/tinyllava/conversation.py), following `conv_vicuna_v1`.

**Comment by eternalding** [comment]
Got it. Thanks. I'll close the issue.
